# Generated by Django 5.2 on 2026-05-18 03:50

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='products/categories/', verbose_name='Hình ảnh')),
                ('icon', models.CharField(blank=True, help_text='VD: fas fa-camera, fas fa-shield-alt', max_length=100, verbose_name='Icon (FontAwesome)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('short_desc', models.TextField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='products/', verbose_name='Hình ảnh chính')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Thương hiệu')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('specifications', models.TextField(blank=True, verbose_name='Thông số kỹ thuật')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật (hiện trang chủ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='products/gallery/', verbose_name='Hình ảnh')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Gallery sản phẩm',
                'ordering': ['order'],
            },
        ),
    ]
