# Generated by Django 5.2 on 2026-06-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Để trống = danh mục cấp 1. Chọn danh mục khác để biến mục này thành con.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='Danh mục cha'),
        ),
    ]
