# Generated by Django 5.2 on 2026-05-18 03:50

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đối tác')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[300, 150], upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('partner_type', models.CharField(choices=[('partner', 'Đối tác'), ('agent', 'Đại lý chính thức'), ('supplier', 'Nhà cung cấp'), ('customer', 'Khách hàng tiêu biểu')], default='partner', max_length=20, verbose_name='Loại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác & Đại lý',
                'ordering': ['order'],
            },
        ),
    ]
