# Generated by Django 5.2 on 2026-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
    ]
