# Generated by Django 5.2 on 2026-05-18 04:40

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (FontAwesome)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Danh mục dự án',
                'verbose_name_plural': 'Danh mục dự án',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tên dự án')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('short_desc', models.TextField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[900, 600], upload_to='projects/', verbose_name='Ảnh đại diện')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Khách hàng')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Địa điểm')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm thực hiện')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật (hiện trang chủ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1200, 800], upload_to='projects/gallery/', verbose_name='Hình ảnh')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Hình ảnh dự án',
                'verbose_name_plural': 'Hình ảnh dự án',
                'ordering': ['order'],
            },
        ),
    ]
