# Generated by Django 5.2 on 2026-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcategory_show_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
