# Generated by Django 5.2 on 2026-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_slug_alter_projectcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
    ]
