# Generated by Django 5.2 on 2026-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_slug_alter_newscategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã đăng')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
    ]
