# Generated by Django 5.2 on 2026-06-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_published_at_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_guid',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='GUID nguồn'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link gốc'),
        ),
        migrations.CreateModel(
            name='RssSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nguồn')),
                ('feed_url', models.URLField(max_length=500, verbose_name='URL RSS feed')),
                ('author', models.CharField(blank=True, help_text='Để trống → dùng tác giả của feed hoặc mặc định.', max_length=100, verbose_name='Tác giả (ghi đè)')),
                ('max_items', models.PositiveSmallIntegerField(default=10, verbose_name='Số bài tối đa mỗi lần')),
                ('use_ai', models.BooleanField(default=True, help_text='Bật: Claude viết lại thành bài nguyên gốc. Tắt: lưu nội dung gốc (đã làm sạch HTML).', verbose_name='Dùng AI viết lại')),
                ('ai_instructions', models.TextField(blank=True, help_text='Giọng văn, độ dài, từ khóa SEO… thêm cho AI khi viết lại.', verbose_name='Chỉ dẫn cho AI')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Kích hoạt')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần lấy gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_sources', to='news.newscategory', verbose_name='Danh mục đích')),
            ],
            options={
                'verbose_name': 'Nguồn RSS',
                'verbose_name_plural': 'Nguồn RSS',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.rsssource', verbose_name='Nguồn nhập'),
        ),
    ]
