# Generated by Django 5.2 on 2026-05-18 03:50

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (FontAwesome)')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='services/categories/', verbose_name='Hình ảnh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Danh mục dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tên dịch vụ')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('short_desc', models.TextField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='services/', verbose_name='Hình ảnh')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (FontAwesome)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật (hiện trang chủ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
