# Generated by Django 5.2 on 2026-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Bật để danh mục này xuất hiện trong dropdown menu điều hướng.', verbose_name='Hiển thị trong menu'),
        ),
    ]
