# Generated by Django 5.2 on 2026-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Công ty')),
                ('subject', models.CharField(max_length=300, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('read', 'Đã đọc'), ('replied', 'Đã phản hồi'), ('closed', 'Đã đóng')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phản hồi')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ghi chú admin')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
