# Generated by Django 5.2 on 2026-05-18 03:50

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Tiêu đề phụ')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[700, 500], upload_to='about/', verbose_name='Hình ảnh')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text ảnh')),
                ('button_text', models.CharField(default='Xem thêm', max_length=50, verbose_name='Nút - Text')),
                ('button_url', models.CharField(default='/ve-chung-toi/', max_length=200, verbose_name='Nút - URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Giới thiệu',
                'verbose_name_plural': 'Section Giới thiệu',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ADCARE Việt Nam', max_length=200, verbose_name='Tên công ty')),
                ('company_name_en', models.CharField(blank=True, max_length=200, verbose_name='Tên tiếng Anh')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 100], upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='Email 2')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('zalo_url', models.URLField(blank=True, verbose_name='Zalo')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps (iframe)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Website',
                'verbose_name_plural': 'Cấu hình Website',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 800], upload_to='sliders/', verbose_name='Hình ảnh')),
                ('button_text', models.CharField(default='Xem thêm', max_length=50, verbose_name='Nút 1 - Text')),
                ('button_url', models.CharField(default='#', max_length=200, verbose_name='Nút 1 - URL')),
                ('button2_text', models.CharField(blank=True, max_length=50, verbose_name='Nút 2 - Text')),
                ('button2_url', models.CharField(blank=True, max_length=200, verbose_name='Nút 2 - URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide Banner',
                'verbose_name_plural': 'Slide Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-users', help_text='VD: fas fa-users, fas fa-project-diagram', max_length=60, verbose_name='Icon (FontAwesome)')),
                ('number', models.CharField(help_text='VD: 100+, 1000+', max_length=20, verbose_name='Số liệu')),
                ('label', models.CharField(max_length=100, verbose_name='Nhãn')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả phụ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Chỉ số thống kê',
                'verbose_name_plural': 'Các chỉ số thống kê',
                'ordering': ['order'],
            },
        ),
    ]
