# Generated by Django 5.2 on 2026-05-18 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='VD: fas fa-check-circle, fas fa-shield-alt', max_length=60, verbose_name='Icon (FontAwesome)')),
                ('text', models.CharField(max_length=200, verbose_name='Nội dung')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.aboutsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Điểm nổi bật',
                'verbose_name_plural': 'Điểm nổi bật',
                'ordering': ['order'],
            },
        ),
    ]
