# Generated by Django 5.2 on 2026-05-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_description',
            field=models.TextField(blank=True, help_text='Đoạn giới thiệu ngắn hiển thị ở footer. Để trống sẽ dùng slogan.', verbose_name='Mô tả footer'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='working_hours',
            field=models.TextField(blank=True, default='Thứ 2 - Thứ 7: 8:00 - 17:30\nChủ nhật: 8:00 - 12:00', help_text='Mỗi dòng một khung giờ. VD: Thứ 2 - Thứ 7: 8:00 - 17:30', verbose_name='Giờ làm việc'),
        ),
    ]
