# Generated by Django 5.2 on 2026-05-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_footer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('item_type', models.CharField(choices=[('home', 'Trang chủ'), ('about', 'Về chúng tôi'), ('products', 'Sản phẩm (+ dropdown danh mục)'), ('services', 'Dịch vụ (+ dropdown danh mục)'), ('projects', 'Dự án'), ('news', 'Tin tức'), ('contact', 'Liên hệ'), ('custom', 'Link tùy chỉnh')], default='custom', max_length=20, verbose_name='Loại')),
                ('url', models.CharField(blank=True, help_text='Chỉ dùng cho loại "Link tùy chỉnh". VD: /gioi-thieu/', max_length=200, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Mở tab mới')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu chính',
                'ordering': ['order'],
            },
        ),
    ]
