# Generated by Django 5.2 on 2026-05-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_default_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, help_text='Dùng cho kiểu dropdown Mega menu.', max_length=200, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dropdown_style',
            field=models.CharField(choices=[('list', 'Danh sách đơn giản'), ('grid', 'Lưới 2 cột (có icon)'), ('mega', 'Mega menu (có mô tả)')], default='list', help_text='Chỉ áp dụng khi menu cấp 1 có menu con.', max_length=10, verbose_name='Kiểu dropdown'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='VD: fas fa-camera. Dùng cho kiểu dropdown Lưới/Mega.', max_length=60, verbose_name='Icon (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Để trống = menu cấp 1. Chọn menu cha = menu con (dropdown).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Menu cha'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('home', 'Trang chủ'), ('about', 'Về chúng tôi'), ('products', 'Sản phẩm (+ dropdown danh mục)'), ('services', 'Dịch vụ (+ dropdown danh mục)'), ('projects', 'Dự án'), ('news', 'Tin tức'), ('contact', 'Liên hệ'), ('custom', 'Link tùy chỉnh')], default='custom', max_length=20, verbose_name='Loại trang'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Bắt buộc với loại "Link tùy chỉnh". VD: /gioi-thieu/', max_length=200, verbose_name='URL'),
        ),
    ]
