# Generated by Django 5.2 on 2026-05-22 06:31

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    _VI_CHARS = {
        'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a',
        'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e',
        'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i',
        'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o', 'ø': 'o',
        'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u',
        'ý': 'y', 'ÿ': 'y', 'ç': 'c', 'ñ': 'n',
        'đ': 'd', 'Đ': 'd',
        'ă': 'a', 'ắ': 'a', 'ằ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
        'Ă': 'a', 'Ắ': 'a', 'Ằ': 'a', 'Ẳ': 'a', 'Ẵ': 'a', 'Ặ': 'a',
        'ấ': 'a', 'ầ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a',
        'Â': 'a', 'Ấ': 'a', 'Ầ': 'a', 'Ẩ': 'a', 'Ẫ': 'a', 'Ậ': 'a',
        'ế': 'e', 'ề': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
        'Ê': 'e', 'Ế': 'e', 'Ề': 'e', 'Ể': 'e', 'Ễ': 'e', 'Ệ': 'e',
        'ố': 'o', 'ồ': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o',
        'Ô': 'o', 'Ố': 'o', 'Ồ': 'o', 'Ổ': 'o', 'Ỗ': 'o', 'Ộ': 'o',
        'ơ': 'o', 'ớ': 'o', 'ờ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
        'Ơ': 'o', 'Ớ': 'o', 'Ờ': 'o', 'Ở': 'o', 'Ỡ': 'o', 'Ợ': 'o',
        'ư': 'u', 'ứ': 'u', 'ừ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
        'Ư': 'u', 'Ứ': 'u', 'Ừ': 'u', 'Ử': 'u', 'Ữ': 'u', 'Ự': 'u',
        'ỉ': 'i', 'ị': 'i', 'Ỉ': 'i', 'Ị': 'i',
        'ũ': 'u', 'ủ': 'u', 'ụ': 'u', 'Ũ': 'u', 'Ủ': 'u', 'Ụ': 'u',
        'ĩ': 'i', 'Ĩ': 'i',
        'ỳ': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y',
        'Ỳ': 'y', 'Ỷ': 'y', 'Ỹ': 'y', 'Ỵ': 'y',
    }

    def vi_slugify(text):
        text = ''.join(_VI_CHARS.get(c, c) for c in text)
        return slugify(text)

    AboutSection = apps.get_model('core', 'AboutSection')
    used_slugs = set()
    for section in AboutSection.objects.all():
        if not section.title:
            continue
        base = vi_slugify(section.title) or f'section-{section.pk}'
        slug = base
        counter = 2
        while slug in used_slugs or AboutSection.objects.filter(slug=slug).exclude(pk=section.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        section.slug = slug
        used_slugs.add(slug)
        section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_menuitem_add_dropdown_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='meta_desc',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Tiêu đề SEO. Để trống sẽ dùng tiêu đề chính.', max_length=200, verbose_name='Meta Title'),
        ),
        # Bước 1: thêm slug không unique, cho phép null tạm thời
        migrations.AddField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, default='', verbose_name='Slug (URL)'),
        ),
        # Bước 2: tự động tạo slug cho các record cũ
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Bước 3: thêm unique constraint sau khi data đã được điền
        migrations.AlterField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Tự động tạo từ tiêu đề. URL trang: /gioi-thieu/&lt;slug&gt;/', max_length=200, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
