# Generated by Django 5.2 on 2026-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_menuitem_add_dropdown_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='meta_desc',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Tiêu đề SEO. Để trống sẽ dùng tiêu đề chính.', max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Tự động tạo từ tiêu đề. URL trang: /gioi-thieu/&lt;slug&gt;/', max_length=200, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
