# Generated by Django 5.2 on 2026-05-22 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutsection_meta_desc_aboutsection_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='auto_add_menu',
            field=models.BooleanField(default=False, help_text='Khi bật, section này sẽ tự động tạo một mục trong menu điều hướng.', verbose_name='Tự động thêm vào menu'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='menu_order',
            field=models.PositiveSmallIntegerField(default=99, verbose_name='Thứ tự trong menu'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='menu_parent',
            field=models.ForeignKey(blank=True, help_text='Chọn menu cha để hiển thị dưới dạng menu con. Để trống = thêm vào menu cấp 1 (menu chính).', limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.menuitem', verbose_name='Hiển thị là menu con của'),
        ),
    ]
