# Generated by Django 5.2 on 2026-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutsection_auto_add_menu_aboutsection_menu_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Bật để section này tự xuất hiện trong dropdown của menu "Về chúng tôi" mà không cần tạo MenuItem.', verbose_name='Hiển thị trong menu dropdown'),
        ),
    ]
