# Generated by Django 5.2 on 2026-05-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutsection_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='pdf_profile',
            field=models.FileField(blank=True, help_text='File PDF hồ sơ năng lực công ty. Sẽ hiển thị nút tải ở trang Giới thiệu và Footer.', upload_to='documents/', verbose_name='Hồ sơ năng lực (PDF)'),
        ),
    ]
