# Generated by Django 5.2 on 2026-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig_add_pdf_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload file PDF để hiển thị nút tải trên trang này.', upload_to='documents/', verbose_name='File PDF (Hồ sơ năng lực)'),
        ),
    ]
