# Generated by Django 5.2 on 2026-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aboutsection_add_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị'),
        ),
    ]
