# Generated by Django 5.2 on 2026-06-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aboutsection_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('home', 'Trang chủ'), ('about', 'Về chúng tôi'), ('products', 'Sản phẩm (+ dropdown danh mục)'), ('services', 'Dịch vụ (+ dropdown danh mục)'), ('solutions', 'Giải pháp (+ dropdown danh mục)'), ('projects', 'Dự án'), ('news', 'Tin tức'), ('contact', 'Liên hệ'), ('custom', 'Link tùy chỉnh')], default='custom', max_length=20, verbose_name='Loại trang'),
        ),
    ]
