# Generated by Django 5.2 on 2026-06-09 01:54

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (FontAwesome)')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='solutions/categories/', verbose_name='Hình ảnh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị')),
                ('show_in_menu', models.BooleanField(default=True, help_text='Bật để danh mục này xuất hiện trong dropdown menu điều hướng.', verbose_name='Hiển thị trong menu')),
                ('parent', models.ForeignKey(blank=True, help_text='Để trống = danh mục cấp 1. Chọn danh mục khác để biến mục này thành con.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='solutions.solutioncategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục giải pháp',
                'verbose_name_plural': 'Danh mục giải pháp',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tên giải pháp')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_desc', models.TextField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='solutions/', verbose_name='Hình ảnh')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (FontAwesome)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật (hiện trang chủ)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='solutions.solutioncategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Giải pháp',
                'verbose_name_plural': 'Giải pháp',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
